version: '3.8'
services:
  frontend:
    build: ./todo-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000

  backend:
    build: ./graphql-todo-server
    ports:
      - "4000:4000"

